"""Updated Key

Revision ID: 3377e7622ca6
Revises: dd7dad5023f5
Create Date: 2026-03-05 18:28:29.979972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3377e7622ca6'
down_revision: Union[str, Sequence[str], None] = 'dd7dad5023f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'file_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('file_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
