"""initial schema

Revision ID: dd7dad5023f5
Revises: 
Create Date: 2026-03-02 18:58:04.094483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7dad5023f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('court', sa.String(length=255), nullable=False),
    sa.Column('case_number', sa.String(length=255), nullable=False),
    sa.Column('respondents', sa.Text(), nullable=False),
    sa.Column('petitioners', sa.Text(), nullable=False),
    sa.Column('decision_date', sa.Date(), nullable=True),
    sa.Column('citation', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_case_number'), 'cases', ['case_number'], unique=False)
    op.create_index(op.f('ix_cases_decision_date'), 'cases', ['decision_date'], unique=False)
    op.create_table('case_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_chunks_case_id'), 'case_chunks', ['case_id'], unique=False)
    op.create_index('ix_case_chunks_case_id_chunk_index', 'case_chunks', ['case_id', 'chunk_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_chunks_case_id_chunk_index', table_name='case_chunks')
    op.drop_index(op.f('ix_case_chunks_case_id'), table_name='case_chunks')
    op.drop_table('case_chunks')
    op.drop_index(op.f('ix_cases_decision_date'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_number'), table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
